#!usr/bin/env python3
# ===========================================================
# 16/04/2019
# This script is a first aproximation to extract flexpart
# output information using python
# ===========================================================

import os
from netCDF4 import Dataset

# == Extract Data ===========================================
def extract_nc(filePath):
    '''
    This function extract the airtracer variable from a 
    netCDF4 file generated by FLEXPART.

    It return a tuple containing the time, height, latitude,
    longitude and the airtracer data. 
    The airtracer is an array with 4 dimensions related to time,
    latiude and longitude, in that order. 
    '''
    # Create a dataset
    data = Dataset(filePath)
    # Extract the variables
    # (!) To see the keys use data.variables.keys()
    time_nc = data.variables['time']
    lon_nc = data.variables['longitude']
    lat_nc = data.variables['latitude']
    hgt_nc = data.variables['height']
    airtracer_nc = data.variables['spec001_mr']
    # <= Here is the place to add more variables to extract

    # Data comes in a class called 'netCDF4._netCDF4.Variable',
    # we just need an array.
    time = time_nc[:]
    lon = lon_nc[:]
    lat = lat_nc[:]
    hgt = hgt_nc[:]
    airtracer = airtracer_nc[0, 0, :]  # First two dims are irrelevant
    # Return data
    return (time, hgt, lat, lon, airtracer)
# ===========================================================

# == Plot Data ==============================================


# ===========================================================


if __name__ == '__main__':
    # == Define parameters ==================================
    # Path to some grid files
    dataPath = 'testData/output_03_MassPlumeTrajectories_netCDF/'
    # =======================================================

    # == Find data files ====================================
    # First we extract all the files inside output dir
    files_all = os.listdir(dataPath)
    # Take only files ending with '.nc'
    files_nc = [f for f in files_all if f.endswith('.nc') == True]
    # Choose the file
    filePath = dataPath + files_nc[0]
    # =======================================================

    # == Extract the data ===================================
    # Call 'extract_nc'
    data = extract_nc(filePath)
